### ISSUE TITLE
test_find__with_directory fails on windows

### ISSUE THREAD

**Issue by tritium21** [defunkt/pystache#162]
The failure in question is as follows:

```
(_venv) C:\Users\alex\Documents\GitHub\chargen [master]> pystache-test
pystache: running tests: argv: ['C:\\Users\\alex\\Documents\\GitHub\\chargen\\_venv\\Scripts\\pystache-test-script.py']
......................................................................................................................................................................................................................................F......................
======================================================================
FAIL: test_find__with_directory (pystache.tests.test_specloader.TemplateSpecTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alex\Documents\GitHub\chargen\_venv\lib\site-packages\pystache\tests\test_specloader.py", line 392, in test_find__with_directory
    self.assertPaths(actual, expected)
  File "C:\Users\alex\Documents\GitHub\chargen\_venv\lib\site-packages\pystache\tests\test_specloader.py", line 38, in assertPaths
    self.assertEqual(actual, expected)
AssertionError: 'C:\\Users\\alex\\Documents\\GitHub\\chargen\\_venv\\lib\\site-packages\\pystache\\tests\\data\\foo\\bar.txt' != 'C:\\Users\\alex\\Documents\\GitHub\\chargen\\_venv\\lib\\site-packages\\pystache\\tests\\data\\foo/bar.txt'

----------------------------------------------------------------------
Ran 253 tests in 0.140s

FAILED (failures=1)
(_venv) C:\Users\alex\Documents\GitHub\chargen [master]>
```

Looking at the code it looks like you hard code a / into the expected path.  It will never pass on Windows.

**Comment by kevincarrogan** [comment]
Fixed this on master but still need to get this up on PyPI so re-opening until that is done.

**Comment by cjerdonek** [comment]
@kevincarrogan also make sure you merge changes in master to the develop branch, where development for 0.6 is happening IIRC.

**Comment by kevincarrogan** [comment]
Done. I don't have access to push to PyPI those latest changes so either someone else could do that for me or could I get access @cjerdonek? kevindmorgan is my PyPI username.

**Comment by cjerdonek** [comment]
Hi @kevincarrogan, I can give you access.  Just give me a day or two ... thanks.

**Comment by cjerdonek** [comment]
By the way @kevincarrogan, be sure to study the instructions for maintainers in the [`setup.py`](https://github.com/defunkt/pystache/blob/master/setup.py#L7) docstring.  In particular, I noticed you also need to update the `HISTORY.md` file.

**Comment by cjerdonek** [comment]
@kevincarrogan I gave you Maintainer access on PyPI.
